### ISSUE TITLE
rails-footnotes and current_user

### ISSUE THREAD

**Issue by masciugo** [josevalim/rails-footnotes#128]
[is this a bug?](http://stackoverflow.com/questions/29280893/rails-footnotes-and-current-user)

**Comment by Intrepidd** [comment]
I guess we could pass the controller to the ``enabled`` lambda so you can do something like this :

```ruby
f.enabled = -> { |controller| controller.current_user.admin? }
```

I'll have a look shortly

**Comment by Intrepidd** [comment]
Fixed in master

**Comment by masciugo** [comment]
still persisting..
    
    masciugo@gr-toniolo-iMac5 ~/dev/ibra $ bundle list rails-footnotes
    /Users/masciugo/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/rails-footnotes-768fa4f2cbd5
    masciugo@gr-toniolo-iMac5 ~/dev/ibra $ rails s
    => Booting Thin
    => Rails 3.2.21 application starting in development on http://0.0.0.0:3000
    => Call with -d to detach
    => Ctrl-C to shutdown server
    clinic_id encryption disabled
    Exiting
    /Users/masciugo/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:245:in `load': /Users/masciugo/dev/ibra/config/initializers/rails_footnotes.rb:7: syntax error, unexpected '|' (SyntaxError)
      f.enabled = -> { |controller| controller.current_user.try(:admin?) }
                        ^
      from /Users/masciugo/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:245:in `block in load'
      from /Users/masciugo/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
      from /Users/masciugo/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:245:in `load'
      from /Users/masciugo/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-3.2.21/lib/rails/engine.rb:593:in `block (2 levels) in <class:Engine>'
      from /Users/masciugo/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-3.2.21/lib/rails/engine.rb:592:in `each'
      from /Users/masciugo/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-3.2.21/lib/rails/engine.rb:592:in `block in <class:Engine>'
      from /Users/masciugo/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-3.2.21/lib/rails/initializable.rb:30:in `instance_exec'
      from /Users/masciugo/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-3.2.21/lib/rails/initializable.rb:30:in `run'
      from /Users/masciugo/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-3.2.21/lib/rails/initializable.rb:55:in `block in run_initializers'
      from /Users/masciugo/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-3.2.21/lib/rails/initializable.rb:54:in `each'
      from /Users/masciugo/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-3.2.21/lib/rails/initializable.rb:54:in `run_initializers'
      from /Users/masciugo/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-3.2.21/lib/rails/application.rb:136:in `initialize!'
      from /Users/masciugo/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-3.2.21/lib/rails/railtie/configurable.rb:30:in `method_missing'
      from /Users/masciugo/dev/ibra/config/environment.rb:5:in `<top (required)>'
      from /Users/masciugo/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
      from /Users/masciugo/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `block in require'
      from /Users/masciugo/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
      from /Users/masciugo/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
      from /Users/masciugo/dev/ibra/config.ru:3:in `block in <main>'
      from /Users/masciugo/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.4.5/lib/rack/builder.rb:51:in `instance_eval'
      from /Users/masciugo/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.4.5/lib/rack/builder.rb:51:in `initialize'
      from /Users/masciugo/dev/ibra/config.ru:in `new'
      from /Users/masciugo/dev/ibra/config.ru:in `<main>'
      from /Users/masciugo/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.4.5/lib/rack/builder.rb:40:in `eval'
      from /Users/masciugo/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.4.5/lib/rack/builder.rb:40:in `parse_file'
      from /Users/masciugo/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.4.5/lib/rack/server.rb:200:in `app'
      from /Users/masciugo/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-3.2.21/lib/rails/commands/server.rb:46:in `app'
      from /Users/masciugo/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.4.5/lib/rack/server.rb:304:in `wrapped_app'
      from /Users/masciugo/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.4.5/lib/rack/server.rb:254:in `start'
      from /Users/masciugo/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-3.2.21/lib/rails/commands/server.rb:70:in `start'
      from /Users/masciugo/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-3.2.21/lib/rails/commands.rb:55:in `block in <top (required)>'
      from /Users/masciugo/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-3.2.21/lib/rails/commands.rb:50:in `tap'
      from /Users/masciugo/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-3.2.21/lib/rails/commands.rb:50:in `<top (required)>'
      from bin/rails:10:in `require'
      from bin/rails:10:in `<main>'

**Comment by Intrepidd** [comment]
My bad, you can't accept arguments with the ``-> {}`` lamda syntax, I updated my answer

**Comment by masciugo** [comment]
ok, thank you.

    f.enabled = proc { |controller| controller.current_user.try(:admin?) }
